"""
A/B test deployer — Enterprise tier only.

Usage:
    python tools/deploy_ab_test.py \
        --client-slug <slug> \
        --test-name <name> \
        --variant-a <path_or_html> \
        --variant-b <path_or_html>

Creates the AB test in the DB, generates an instrumented HTML snippet with
inline JS for 50/50 assignment + beacon events, and saves it to
output/ab_tests/{slug}/{test_id}_deployed.html.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

try:
    from dotenv import load_dotenv
    load_dotenv(PROJECT_ROOT / ".env")
except ImportError:
    pass

import importlib.util as _ilu

def _load_db():
    spec = _ilu.spec_from_file_location("db", PROJECT_ROOT / "tools" / "db.py")
    mod = _ilu.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

db = _load_db()

BEACON_URL = os.getenv("AB_BEACON_URL", "http://localhost:5050")

# ---------------------------------------------------------------------------
# HTML helpers
# ---------------------------------------------------------------------------

def _read_variant(value: str) -> str:
    """Accept a file path or a raw HTML string."""
    p = Path(value)
    if p.exists() and p.is_file():
        return p.read_text(encoding="utf-8")
    return value


def _build_instrumented_html(
    test_id: int,
    client_slug: str,
    variant_a_html: str,
    variant_b_html: str,
) -> str:
    beacon = BEACON_URL.rstrip("/")
    js = f"""<script>
(function() {{
  var TEST_ID = {test_id};
  var CLIENT_SLUG = "{client_slug}";
  var BEACON = "{beacon}";
  var COOKIE_NAME = "abt_" + TEST_ID;

  function getCookie(name) {{
    var m = document.cookie.match("(?:^|; )" + name + "=([AB])");
    return m ? m[1] : null;
  }}

  var variant = getCookie(COOKIE_NAME);
  if (!variant) {{
    variant = Math.random() < 0.5 ? "A" : "B";
    var expires = new Date(Date.now() + 30 * 24 * 3600 * 1000).toUTCString();
    document.cookie = COOKIE_NAME + "=" + variant + ";path=/;expires=" + expires + ";SameSite=Lax";
  }}

  document.querySelectorAll("[data-abt-variant]").forEach(function(el) {{
    el.style.display = el.getAttribute("data-abt-variant") === variant ? "" : "none";
  }});

  function sendBeacon(eventType, sessionId) {{
    var payload = JSON.stringify({{
      test_id: TEST_ID,
      client_slug: CLIENT_SLUG,
      variant: variant,
      event_type: eventType,
      session_id: sessionId || document.cookie
    }});
    if (navigator.sendBeacon) {{
      navigator.sendBeacon(BEACON + "/beacon", new Blob([payload], {{type: "application/json"}}));
    }} else {{
      fetch(BEACON + "/beacon", {{
        method: "POST",
        headers: {{"Content-Type": "application/json"}},
        body: payload,
        keepalive: true
      }}).catch(function() {{}});
    }}
  }}

  window.abTrack = function(eventType) {{ sendBeacon(eventType, null); }};

  sendBeacon("pageview", null);
}})();
</script>"""

    return f"""<!-- AB Test ID: {test_id} — generated by deploy_ab_test.py -->
{js}
<div data-abt-variant="A">
{variant_a_html}
</div>
<div data-abt-variant="B" style="display:none">
{variant_b_html}
</div>
<!-- /AB Test ID: {test_id} -->"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Cifra A/B test deployer (Enterprise only)")
    parser.add_argument("--client-slug", required=True, help="Client slug in DB")
    parser.add_argument("--test-name", required=True, help="Human-readable test name")
    parser.add_argument("--variant-a", required=True, help="File path or raw HTML for variant A")
    parser.add_argument("--variant-b", required=True, help="File path or raw HTML for variant B")
    args = parser.parse_args()

    db.init_db()

    client = db.get_client(args.client_slug)
    if not client:
        print(f"ERROR: Client '{args.client_slug}' not found in DB.")
        sys.exit(1)

    tier = (client.get("tier") or "").lower()
    if tier != "enterprise":
        print(
            f"ERROR: A/B testing is restricted to enterprise-tier clients only.\n"
            f"Client '{args.client_slug}' is on the '{tier}' tier.\n"
            f"Upgrade the client to enterprise before running A/B tests."
        )
        sys.exit(1)

    variant_a = _read_variant(args.variant_a)
    variant_b = _read_variant(args.variant_b)

    test_id = db.start_ab_test(
        client_slug=args.client_slug,
        test_name=args.test_name,
        variant_a=variant_a,
        variant_b=variant_b,
    )
    print(f"Created A/B test #{test_id}: '{args.test_name}' for {args.client_slug}")

    instrumented = _build_instrumented_html(test_id, args.client_slug, variant_a, variant_b)

    output_dir = PROJECT_ROOT / "output" / "ab_tests" / args.client_slug
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{test_id}_deployed.html"
    out_path.write_text(instrumented, encoding="utf-8")

    print(f"\nDeployed snippet: {out_path}")
    print(f"Beacon endpoint:  {BEACON_URL}/beacon")
    print(f"\nNext steps:")
    print(f"  1. Start the beacon if not running:  python tools/ab_test_beacon.py")
    print(f"  2. Replace the target section in index.html with the contents of:")
    print(f"     {out_path}")
    print(f"  3. Add conversion tracking to CTA buttons:")
    print(f"     <button onclick=\"window.abTrack('conversion')\">...</button>")
    print(f"  4. The winning variant will be promoted automatically after 14 days or 1000 visitors.")

    result = {
        "test_id": test_id,
        "client_slug": args.client_slug,
        "test_name": args.test_name,
        "beacon_url": f"{BEACON_URL}/beacon",
        "deployed_snippet": str(out_path),
        "status": "running",
    }
    print(f"\n{json.dumps(result, indent=2)}")


if __name__ == "__main__":
    main()
