"""
send_outreach_email.py

Usage:
    python tools/send_outreach_email.py --lead-id 42 [--dry-run]

Generates a personalized Spanish cold email for the lead using Claude
(claude-haiku-4-5), then sends it via tools/email_sender.py.

Rules:
    - Aborts if today's send count >= 50 (email_sender.py enforces this too)
    - Updates lead status to 'contacted' (unless already past that stage)
    - Logs every send to the outreach_log table (even dry-runs)
    - Email is under 120 words, professional Spanish, no AI-slop phrases
    - Includes the demo preview URL if output/demos/{slug}/index.html exists

Requires: ANTHROPIC_API_KEY in .env
"""

import sys
import io
import os
import re
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

sys.path.insert(0, str(Path(__file__).parent.parent))
from tools.db import get_lead, add_outreach_log, mark_lead_contacted

try:
    import anthropic
except ImportError:
    print("[ERROR] anthropic SDK not installed. Run: pip install anthropic")
    sys.exit(1)

# Status values that should not be overridden by 'contacted'
_PAST_CONTACTED = {"demo_sent", "in_conversation", "won", "lost"}

WEBSITE_STATUS_OBSERVATIONS = {
    "no_site": (
        "no tiene presencia web en absoluto, lo que significa que sus clientes potenciales "
        "no pueden encontrarles fuera de Google Maps"
    ),
    "broken": (
        "su sitio web actual no carga correctamente, lo que genera una primera impresión "
        "negativa y pérdida de clientes"
    ),
    "outdated": (
        "su sitio web existe pero parece desactualizado — sin diseño adaptado a móviles "
        "ni HTTPS — lo que afecta su posicionamiento en Google"
    ),
    "modern": (
        "su sitio web es funcional, aunque vemos oportunidades claras de mejora en "
        "conversión y posicionamiento local"
    ),
}


def _business_slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def _demo_url(slug: str) -> str | None:
    demo_path = Path(f"output/demos/{slug}/index.html")
    if demo_path.exists():
        return f"http://localhost:3000/output/demos/{slug}/index.html"
    return None


def _count_today_sends() -> int:
    log_path = Path("data/email_log.jsonl")
    if not log_path.exists():
        return 0
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    count = 0
    with open(log_path, encoding="utf-8") as f:
        for line in f:
            try:
                record = json.loads(line)
                if record.get("ts", "").startswith(today) and record.get("status") == "sent":
                    count += 1
            except json.JSONDecodeError:
                continue
    return count


def generate_email(lead: dict, demo_url: str | None) -> tuple[str, str]:
    """Return (subject, body_html) generated by Claude Haiku."""
    client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

    observation = WEBSITE_STATUS_OBSERVATIONS.get(
        lead.get("website_status", ""), WEBSITE_STATUS_OBSERVATIONS["broken"]
    )
    demo_line = (
        f"He preparado una muestra gratuita de cómo podría quedar su nuevo sitio: {demo_url}"
        if demo_url
        else ""
    )

    prompt = f"""Escribe un email frío en español para un negocio llamado "{lead['business_name']}"
en el sector "{lead.get('sector', 'local')}", ubicado en "{lead.get('region', 'España')}".

Contexto: {observation}.

{demo_line}

Reglas estrictas:
- Menos de 120 palabras en el cuerpo
- Tono profesional, directo, respetuoso — nada de frases genéricas de marketing
- Una sola llamada a la acción: responder para agendar una llamada de 15 min
- Sin emojis, sin exclamaciones múltiples, sin palabras prohibidas como "innovador", "solución", "sinergias"
- Firma: Adrián, Cifra Web

Responde con JSON exacto en este formato:
{{
  "subject": "línea de asunto del email",
  "body_text": "cuerpo del email en texto plano"
}}"""

    message = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=512,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = message.content[0].text.strip()
    # Strip markdown code fences if present
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)
    data = json.loads(raw)

    subject = data["subject"]
    body_text = data["body_text"]

    body_html = f"""<div style="font-family: Georgia, serif; font-size: 15px; line-height: 1.7; color: #1A1410; max-width: 600px;">
<p>{body_text.replace(chr(10), '<br>')}</p>
</div>"""

    return subject, body_html


def run(lead_id: int, dry_run: bool = False) -> dict:
    lead = get_lead(lead_id)
    if not lead:
        print(f"[ERROR] Lead {lead_id} not found.")
        sys.exit(1)

    if not lead.get("email"):
        print(f"[ERROR] Lead {lead_id} ({lead['business_name']}) has no email address.")
        sys.exit(1)

    # Rate limit check
    today_count = _count_today_sends()
    if today_count >= 50:
        print(f"[ABORT] Daily send limit reached ({today_count}/50). Try again tomorrow.")
        sys.exit(1)

    print(f"\n[Outreach] Lead #{lead_id}: {lead['business_name']}")
    print(f"  Email   : {lead['email']}")
    print(f"  Status  : {lead.get('website_status', 'unknown')}")
    print(f"  Sends today: {today_count}/50")

    slug = _business_slug(lead["business_name"])
    demo_url = _demo_url(slug)
    if demo_url:
        print(f"  Demo URL: {demo_url}")

    print("\n  Generating email with Claude Haiku...")
    subject, body_html = generate_email(lead, demo_url)
    print(f"  Subject : {subject}")

    # Import here to allow dry-run without email credentials
    from tools.email_sender import send_email

    result = send_email(
        to=lead["email"],
        subject=subject,
        body_html=body_html,
        dry_run=dry_run,
    )

    # Log to DB regardless of dry_run
    add_outreach_log(lead_id, lead["email"], subject, body_html)

    # Advance status only if not already further in pipeline
    if lead.get("status") not in _PAST_CONTACTED:
        mark_lead_contacted(lead_id)

    status_msg = "[DRY RUN]" if dry_run else "[SENT]"
    print(f"\n  {status_msg} Email logged. Lead status → contacted")
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Send cold outreach email to a lead")
    parser.add_argument("--lead-id", type=int, required=True)
    parser.add_argument("--dry-run", action="store_true", help="Generate email but do not send")
    args = parser.parse_args()
    run(args.lead_id, dry_run=args.dry_run)
